#!/usr/bin/env node
/**
 * Build sırasında çalışır.
 * package.json'daki version'ı okuyup src/version.ts'i otomatik üretir.
 *
 * Böylece tek source of truth = package.json kalır.
 * `npm version <patch|minor|major>` yapınca version.ts otomatik güncellenir.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const packageJsonPath = join(root, "package.json");
const versionTsPath = join(root, "src", "version.ts");

const pkg = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
const version = pkg.version;
const pakAdi = pkg.name; // "@thorrangonak/kanka"

if (!version || typeof version !== "string") {
	console.error("❌ package.json'da geçerli version yok");
	process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/generate-version.mjs
// Bu dosyayı manuel düzenleme — kaynak: package.json
// Build sırasında otomatik güncellenir.

/** Kanka'nın mevcut versiyonu (package.json'dan senkronize). */
export const KANKA_VERSION = "${version}";

/** npm paket adı (registry'de yayınlandığı isim). */
export const PAKET_ADI = "${pakAdi}";
`;

writeFileSync(versionTsPath, content, "utf-8");
console.log(`✓ src/version.ts üretildi: KANKA_VERSION = "${version}"`);
