// AUTO-GENERATED by scripts/generate-version.mjs
// Bu dosyayı manuel düzenleme — kaynak: package.json
// Build sırasında otomatik güncellenir.

/** Kanka'nın mevcut versiyonu (package.json'dan senkronize). */
export const KANKA_VERSION = "0.5.0";

/** npm paket adı (registry'de yayınlandığı isim). */
export const PAKET_ADI = "@thorrangonak/kanka";
